/**
 * This file generated by Apso.
 */
import { AvailabilityModule } from './Availability/Availability.module';
import { BookingModule } from './Booking/Booking.module';
import { ReminderModule } from './Reminder/Reminder.module';
import { CancellationModule } from './Cancellation/Cancellation.module';

export default [
  AvailabilityModule,
  BookingModule,
  ReminderModule,
  CancellationModule,
];
