/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Booking } from './Booking.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { BookingService } from './Booking.service';
import { BookingController } from './Booking.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Booking])],
  providers: [BookingService],
  exports: [BookingService],
  controllers: [BookingController],
})
export class BookingModule {}
