/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Booking, BookingCreate } from './dtos/Booking.dto';
import { BookingController } from './Booking.controller';
import { BookingService } from './Booking.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('BookingController', () => {
  let controller: BookingController;
  let spyService: BookingService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: BookingService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [BookingController],
      providers: [BookingService, ApiServiceProvider],
    }).compile();

    controller = module.get<BookingController>(BookingController);
    spyService = module.get<BookingService>(BookingService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call BookingController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call BookingController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Booking();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
