/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Cancellation, CancellationCreate } from './dtos/Cancellation.dto';
import { CancellationController } from './Cancellation.controller';
import { CancellationService } from './Cancellation.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('CancellationController', () => {
  let controller: CancellationController;
  let spyService: CancellationService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: CancellationService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [CancellationController],
      providers: [CancellationService, ApiServiceProvider],
    }).compile();

    controller = module.get<CancellationController>(CancellationController);
    spyService = module.get<CancellationService>(CancellationService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call CancellationController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call CancellationController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Cancellation();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
