/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Cancellation } from './Cancellation.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { CancellationService } from './Cancellation.service';
import { CancellationController } from './Cancellation.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Cancellation])],
  providers: [CancellationService],
  exports: [CancellationService],
  controllers: [CancellationController],
})
export class CancellationModule {}
