import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class BookingCreate {
  @ApiProperty()
  date: string;
  @ApiProperty()
  time_slot: string;
  @ApiProperty()
  status: string;
  @ApiProperty()
  notes: string;
}

export class Booking {
  @ApiProperty()
  id: number;
  @ApiProperty()
  date: string;
  @ApiProperty()
  time_slot: string;
  @ApiProperty()
  status: string;
  @ApiProperty()
  notes: string;
}
