/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Availability } from './Availability.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { AvailabilityService } from './Availability.service';
import { AvailabilityController } from './Availability.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Availability])],
  providers: [AvailabilityService],
  exports: [AvailabilityService],
  controllers: [AvailabilityController],
})
export class AvailabilityModule {}
