/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Availability, AvailabilityCreate } from './dtos/Availability.dto';
import { AvailabilityController } from './Availability.controller';
import { AvailabilityService } from './Availability.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('AvailabilityController', () => {
  let controller: AvailabilityController;
  let spyService: AvailabilityService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: AvailabilityService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [AvailabilityController],
      providers: [AvailabilityService, ApiServiceProvider],
    }).compile();

    controller = module.get<AvailabilityController>(AvailabilityController);
    spyService = module.get<AvailabilityService>(AvailabilityService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call AvailabilityController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call AvailabilityController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Availability();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
