/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Reminder, ReminderCreate } from './dtos/Reminder.dto';
import { ReminderController } from './Reminder.controller';
import { ReminderService } from './Reminder.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('ReminderController', () => {
  let controller: ReminderController;
  let spyService: ReminderService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: ReminderService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [ReminderController],
      providers: [ReminderService, ApiServiceProvider],
    }).compile();

    controller = module.get<ReminderController>(ReminderController);
    spyService = module.get<ReminderService>(ReminderService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call ReminderController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call ReminderController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Reminder();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
