/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Reminder } from './Reminder.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ReminderService } from './Reminder.service';
import { ReminderController } from './Reminder.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Reminder])],
  providers: [ReminderService],
  exports: [ReminderService],
  controllers: [ReminderController],
})
export class ReminderModule {}
