import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class ReminderCreate {
  @ApiProperty()
  reminder_date: string;
  @ApiProperty()
  reminder_time: string;
  @ApiProperty()
  message: string;
  @ApiProperty()
  is_sent: boolean;
}

export class Reminder {
  @ApiProperty()
  id: number;
  @ApiProperty()
  reminder_date: string;
  @ApiProperty()
  reminder_time: string;
  @ApiProperty()
  message: string;
  @ApiProperty()
  is_sent: boolean;
}
