import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class CancellationCreate {
  @ApiProperty()
  cancellation_date: string;
  @ApiProperty()
  cancellation_time: string;
  @ApiProperty()
  reason: string;
}

export class Cancellation {
  @ApiProperty()
  id: number;
  @ApiProperty()
  cancellation_date: string;
  @ApiProperty()
  cancellation_time: string;
  @ApiProperty()
  reason: string;
}
