import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class AvailabilityCreate {
  @ApiProperty()
  date: string;
  @ApiProperty()
  time_slot: string;
  @ApiProperty()
  available: boolean;
  @ApiProperty()
  location: string;
}

export class Availability {
  @ApiProperty()
  id: number;
  @ApiProperty()
  date: string;
  @ApiProperty()
  time_slot: string;
  @ApiProperty()
  available: boolean;
  @ApiProperty()
  location: string;
}
